name: fullstack-app-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 6'

env:
  NODE_VERSION: 18.x

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18 ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm init
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Print a message
        run: |
          "Hello, Petyo. You pushed to fullstack-app-repo at $(date)."."

#    stage_deploy:
#      runs_on: ubuntu-latest
#      needs: install-build-test
#      environment:
#        name: staging

#      steps:
#        - name: Deploy to Staging
#          run: |
#            echo "Deployed to staging environment"